// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: watcher.proto

package watcherv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_SUCCESS     Status = 1
	Status_STATUS_FAILED      Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SUCCESS",
		2: "STATUS_FAILED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_SUCCESS":     1,
		"STATUS_FAILED":      2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_watcher_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_watcher_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{0}
}

type LastRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=quitsh.watcher.v1.Status" json:"status,omitempty"`
	ScanId        int64                  `protobuf:"varint,2,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	AtUnixMs      int64                  `protobuf:"varint,3,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastRun) Reset() {
	*x = LastRun{}
	mi := &file_watcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastRun) ProtoMessage() {}

func (x *LastRun) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastRun.ProtoReflect.Descriptor instead.
func (*LastRun) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{0}
}

func (x *LastRun) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *LastRun) GetScanId() int64 {
	if x != nil {
		return x.ScanId
	}
	return 0
}

func (x *LastRun) GetAtUnixMs() int64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

type TargetStatus struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TargetId string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// Own inputs only. No dependency propagation.
	Dirty              bool     `protobuf:"varint,2,opt,name=dirty,proto3" json:"dirty,omitempty"`
	HasSuccessfulBuild bool     `protobuf:"varint,3,opt,name=has_successful_build,json=hasSuccessfulBuild,proto3" json:"has_successful_build,omitempty"`
	DirtyInputs        []string `protobuf:"bytes,4,rep,name=dirty_inputs,json=dirtyInputs,proto3" json:"dirty_inputs,omitempty"`
	LastRun            *LastRun `protobuf:"bytes,5,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TargetStatus) Reset() {
	*x = TargetStatus{}
	mi := &file_watcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetStatus) ProtoMessage() {}

func (x *TargetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetStatus.ProtoReflect.Descriptor instead.
func (*TargetStatus) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{1}
}

func (x *TargetStatus) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *TargetStatus) GetDirty() bool {
	if x != nil {
		return x.Dirty
	}
	return false
}

func (x *TargetStatus) GetHasSuccessfulBuild() bool {
	if x != nil {
		return x.HasSuccessfulBuild
	}
	return false
}

func (x *TargetStatus) GetDirtyInputs() []string {
	if x != nil {
		return x.DirtyInputs
	}
	return nil
}

func (x *TargetStatus) GetLastRun() *LastRun {
	if x != nil {
		return x.LastRun
	}
	return nil
}

type GetStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty means all known targets.
	TargetIds []string `protobuf:"bytes,1,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`
	// 0 means the answer must come from a scan started after this request.
	MaxAgeMs      int64 `protobuf:"varint,2,opt,name=max_age_ms,json=maxAgeMs,proto3" json:"max_age_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_watcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

func (x *GetStatusRequest) GetMaxAgeMs() int64 {
	if x != nil {
		return x.MaxAgeMs
	}
	return 0
}

type GetStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ScanId          int64                  `protobuf:"varint,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	ScannedAtUnixMs int64                  `protobuf:"varint,2,opt,name=scanned_at_unix_ms,json=scannedAtUnixMs,proto3" json:"scanned_at_unix_ms,omitempty"`
	Statuses        []*TargetStatus        `protobuf:"bytes,3,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_watcher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetScanId() int64 {
	if x != nil {
		return x.ScanId
	}
	return 0
}

func (x *GetStatusResponse) GetScannedAtUnixMs() int64 {
	if x != nil {
		return x.ScannedAtUnixMs
	}
	return 0
}

func (x *GetStatusResponse) GetStatuses() []*TargetStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type TargetResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=quitsh.watcher.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetResult) Reset() {
	*x = TargetResult{}
	mi := &file_watcher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetResult) ProtoMessage() {}

func (x *TargetResult) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetResult.ProtoReflect.Descriptor instead.
func (*TargetResult) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{4}
}

func (x *TargetResult) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *TargetResult) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

type ReportResultRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scan the caller based its decision on.
	ScanId        int64           `protobuf:"varint,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Results       []*TargetResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_watcher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{5}
}

func (x *ReportResultRequest) GetScanId() int64 {
	if x != nil {
		return x.ScanId
	}
	return 0
}

func (x *ReportResultRequest) GetResults() []*TargetResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReportResultResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Targets whose scan id is no longer resolvable; they stay dirty.
	NotRecorded   []string `protobuf:"bytes,1,rep,name=not_recorded,json=notRecorded,proto3" json:"not_recorded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_watcher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{6}
}

func (x *ReportResultResponse) GetNotRecorded() []string {
	if x != nil {
		return x.NotRecorded
	}
	return nil
}

type RescanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescanRequest) Reset() {
	*x = RescanRequest{}
	mi := &file_watcher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescanRequest) ProtoMessage() {}

func (x *RescanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescanRequest.ProtoReflect.Descriptor instead.
func (*RescanRequest) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{7}
}

type RescanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        int64                  `protobuf:"varint,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescanResponse) Reset() {
	*x = RescanResponse{}
	mi := &file_watcher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescanResponse) ProtoMessage() {}

func (x *RescanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescanResponse.ProtoReflect.Descriptor instead.
func (*RescanResponse) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{8}
}

func (x *RescanResponse) GetScanId() int64 {
	if x != nil {
		return x.ScanId
	}
	return 0
}

type ResetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty means all targets.
	TargetIds     []string `protobuf:"bytes,1,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_watcher_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{9}
}

func (x *ResetRequest) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

type ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_watcher_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{10}
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_watcher_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{11}
}

type InfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	RootDir            string                 `protobuf:"bytes,2,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
	LastScanId         int64                  `protobuf:"varint,3,opt,name=last_scan_id,json=lastScanId,proto3" json:"last_scan_id,omitempty"`
	LastScanAtUnixMs   int64                  `protobuf:"varint,4,opt,name=last_scan_at_unix_ms,json=lastScanAtUnixMs,proto3" json:"last_scan_at_unix_ms,omitempty"`
	LastScanDurationMs int64                  `protobuf:"varint,5,opt,name=last_scan_duration_ms,json=lastScanDurationMs,proto3" json:"last_scan_duration_ms,omitempty"`
	TargetCount        int64                  `protobuf:"varint,6,opt,name=target_count,json=targetCount,proto3" json:"target_count,omitempty"`
	FileCount          int64                  `protobuf:"varint,7,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_watcher_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{12}
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetRootDir() string {
	if x != nil {
		return x.RootDir
	}
	return ""
}

func (x *InfoResponse) GetLastScanId() int64 {
	if x != nil {
		return x.LastScanId
	}
	return 0
}

func (x *InfoResponse) GetLastScanAtUnixMs() int64 {
	if x != nil {
		return x.LastScanAtUnixMs
	}
	return 0
}

func (x *InfoResponse) GetLastScanDurationMs() int64 {
	if x != nil {
		return x.LastScanDurationMs
	}
	return 0
}

func (x *InfoResponse) GetTargetCount() int64 {
	if x != nil {
		return x.TargetCount
	}
	return 0
}

func (x *InfoResponse) GetFileCount() int64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_watcher_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{13}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_watcher_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{14}
}

var File_watcher_proto protoreflect.FileDescriptor

const file_watcher_proto_rawDesc = "" +
	"\n" +
	"\rwatcher.proto\x12\x11quitsh.watcher.v1\"s\n" +
	"\aLastRun\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.quitsh.watcher.v1.StatusR\x06status\x12\x17\n" +
	"\ascan_id\x18\x02 \x01(\x03R\x06scanId\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x03 \x01(\x03R\batUnixMs\"\xcd\x01\n" +
	"\fTargetStatus\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x14\n" +
	"\x05dirty\x18\x02 \x01(\bR\x05dirty\x120\n" +
	"\x14has_successful_build\x18\x03 \x01(\bR\x12hasSuccessfulBuild\x12!\n" +
	"\fdirty_inputs\x18\x04 \x03(\tR\vdirtyInputs\x125\n" +
	"\blast_run\x18\x05 \x01(\v2\x1a.quitsh.watcher.v1.LastRunR\alastRun\"O\n" +
	"\x10GetStatusRequest\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x01 \x03(\tR\ttargetIds\x12\x1c\n" +
	"\n" +
	"max_age_ms\x18\x02 \x01(\x03R\bmaxAgeMs\"\x96\x01\n" +
	"\x11GetStatusResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\x03R\x06scanId\x12+\n" +
	"\x12scanned_at_unix_ms\x18\x02 \x01(\x03R\x0fscannedAtUnixMs\x12;\n" +
	"\bstatuses\x18\x03 \x03(\v2\x1f.quitsh.watcher.v1.TargetStatusR\bstatuses\"^\n" +
	"\fTargetResult\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.quitsh.watcher.v1.StatusR\x06status\"i\n" +
	"\x13ReportResultRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\x03R\x06scanId\x129\n" +
	"\aresults\x18\x02 \x03(\v2\x1f.quitsh.watcher.v1.TargetResultR\aresults\"9\n" +
	"\x14ReportResultResponse\x12!\n" +
	"\fnot_recorded\x18\x01 \x03(\tR\vnotRecorded\"\x0f\n" +
	"\rRescanRequest\")\n" +
	"\x0eRescanResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\x03R\x06scanId\"-\n" +
	"\fResetRequest\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x01 \x03(\tR\ttargetIds\"\x0f\n" +
	"\rResetResponse\"\r\n" +
	"\vInfoRequest\"\x8a\x02\n" +
	"\fInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x19\n" +
	"\broot_dir\x18\x02 \x01(\tR\arootDir\x12 \n" +
	"\flast_scan_id\x18\x03 \x01(\x03R\n" +
	"lastScanId\x12.\n" +
	"\x14last_scan_at_unix_ms\x18\x04 \x01(\x03R\x10lastScanAtUnixMs\x121\n" +
	"\x15last_scan_duration_ms\x18\x05 \x01(\x03R\x12lastScanDurationMs\x12!\n" +
	"\ftarget_count\x18\x06 \x01(\x03R\vtargetCount\x12\x1d\n" +
	"\n" +
	"file_count\x18\a \x01(\x03R\tfileCount\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse*G\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x01\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x022\xfb\x03\n" +
	"\aWatcher\x12V\n" +
	"\tGetStatus\x12#.quitsh.watcher.v1.GetStatusRequest\x1a$.quitsh.watcher.v1.GetStatusResponse\x12_\n" +
	"\fReportResult\x12&.quitsh.watcher.v1.ReportResultRequest\x1a'.quitsh.watcher.v1.ReportResultResponse\x12M\n" +
	"\x06Rescan\x12 .quitsh.watcher.v1.RescanRequest\x1a!.quitsh.watcher.v1.RescanResponse\x12J\n" +
	"\x05Reset\x12\x1f.quitsh.watcher.v1.ResetRequest\x1a .quitsh.watcher.v1.ResetResponse\x12G\n" +
	"\x04Info\x12\x1e.quitsh.watcher.v1.InfoRequest\x1a\x1f.quitsh.watcher.v1.InfoResponse\x12S\n" +
	"\bShutdown\x12\".quitsh.watcher.v1.ShutdownRequest\x1a#.quitsh.watcher.v1.ShutdownResponseB:Z8github.com/sdsc-ordes/quitsh/pkg/watcher/proto;watcherv1b\x06proto3"

var (
	file_watcher_proto_rawDescOnce sync.Once
	file_watcher_proto_rawDescData []byte
)

func file_watcher_proto_rawDescGZIP() []byte {
	file_watcher_proto_rawDescOnce.Do(func() {
		file_watcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_watcher_proto_rawDesc), len(file_watcher_proto_rawDesc)))
	})
	return file_watcher_proto_rawDescData
}

var file_watcher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_watcher_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_watcher_proto_goTypes = []any{
	(Status)(0),                  // 0: quitsh.watcher.v1.Status
	(*LastRun)(nil),              // 1: quitsh.watcher.v1.LastRun
	(*TargetStatus)(nil),         // 2: quitsh.watcher.v1.TargetStatus
	(*GetStatusRequest)(nil),     // 3: quitsh.watcher.v1.GetStatusRequest
	(*GetStatusResponse)(nil),    // 4: quitsh.watcher.v1.GetStatusResponse
	(*TargetResult)(nil),         // 5: quitsh.watcher.v1.TargetResult
	(*ReportResultRequest)(nil),  // 6: quitsh.watcher.v1.ReportResultRequest
	(*ReportResultResponse)(nil), // 7: quitsh.watcher.v1.ReportResultResponse
	(*RescanRequest)(nil),        // 8: quitsh.watcher.v1.RescanRequest
	(*RescanResponse)(nil),       // 9: quitsh.watcher.v1.RescanResponse
	(*ResetRequest)(nil),         // 10: quitsh.watcher.v1.ResetRequest
	(*ResetResponse)(nil),        // 11: quitsh.watcher.v1.ResetResponse
	(*InfoRequest)(nil),          // 12: quitsh.watcher.v1.InfoRequest
	(*InfoResponse)(nil),         // 13: quitsh.watcher.v1.InfoResponse
	(*ShutdownRequest)(nil),      // 14: quitsh.watcher.v1.ShutdownRequest
	(*ShutdownResponse)(nil),     // 15: quitsh.watcher.v1.ShutdownResponse
}
var file_watcher_proto_depIdxs = []int32{
	0,  // 0: quitsh.watcher.v1.LastRun.status:type_name -> quitsh.watcher.v1.Status
	1,  // 1: quitsh.watcher.v1.TargetStatus.last_run:type_name -> quitsh.watcher.v1.LastRun
	2,  // 2: quitsh.watcher.v1.GetStatusResponse.statuses:type_name -> quitsh.watcher.v1.TargetStatus
	0,  // 3: quitsh.watcher.v1.TargetResult.status:type_name -> quitsh.watcher.v1.Status
	5,  // 4: quitsh.watcher.v1.ReportResultRequest.results:type_name -> quitsh.watcher.v1.TargetResult
	3,  // 5: quitsh.watcher.v1.Watcher.GetStatus:input_type -> quitsh.watcher.v1.GetStatusRequest
	6,  // 6: quitsh.watcher.v1.Watcher.ReportResult:input_type -> quitsh.watcher.v1.ReportResultRequest
	8,  // 7: quitsh.watcher.v1.Watcher.Rescan:input_type -> quitsh.watcher.v1.RescanRequest
	10, // 8: quitsh.watcher.v1.Watcher.Reset:input_type -> quitsh.watcher.v1.ResetRequest
	12, // 9: quitsh.watcher.v1.Watcher.Info:input_type -> quitsh.watcher.v1.InfoRequest
	14, // 10: quitsh.watcher.v1.Watcher.Shutdown:input_type -> quitsh.watcher.v1.ShutdownRequest
	4,  // 11: quitsh.watcher.v1.Watcher.GetStatus:output_type -> quitsh.watcher.v1.GetStatusResponse
	7,  // 12: quitsh.watcher.v1.Watcher.ReportResult:output_type -> quitsh.watcher.v1.ReportResultResponse
	9,  // 13: quitsh.watcher.v1.Watcher.Rescan:output_type -> quitsh.watcher.v1.RescanResponse
	11, // 14: quitsh.watcher.v1.Watcher.Reset:output_type -> quitsh.watcher.v1.ResetResponse
	13, // 15: quitsh.watcher.v1.Watcher.Info:output_type -> quitsh.watcher.v1.InfoResponse
	15, // 16: quitsh.watcher.v1.Watcher.Shutdown:output_type -> quitsh.watcher.v1.ShutdownResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_watcher_proto_init() }
func file_watcher_proto_init() {
	if File_watcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_watcher_proto_rawDesc), len(file_watcher_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_watcher_proto_goTypes,
		DependencyIndexes: file_watcher_proto_depIdxs,
		EnumInfos:         file_watcher_proto_enumTypes,
		MessageInfos:      file_watcher_proto_msgTypes,
	}.Build()
	File_watcher_proto = out.File
	file_watcher_proto_goTypes = nil
	file_watcher_proto_depIdxs = nil
}
